version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      include: "scope"
    versioning-strategy: "increase-if-necessary"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
      include: "scope"
    versioning-strategy: "increase-if-necessary"
